#pragma once

#include <string>
#include <cstdlib>
#include <format>
#include <filesystem>

#include "root_directory.h" // configuration file generated by CMake

class FileSystem 
{
private:
    typedef std::string (*Builder) (const std::string &path);

public:
    static std::string GetPath(const std::string &path)
    {
        return GetPathBuilder()(path);
    }

private:
    static std::filesystem::path const &GetRoot();
    static Builder GetPathBuilder();
    static std::string GetPathRelativeRoot(const std::string &path);
    static std::string GetPathRelativeBinary(const std::string &path);
};