#pragma once

#include <string>
#include <cstdlib>
#include <format>

#include "root_directory.h" // configuration file generated by CMake

#ifdef _WIN32
    const char PATH_SEPARATOR {'\\'};
#else
    const char PATH_SEPARATOR {'/'};
#endif

static void ReplaceAll(std::string &str, const std::string &from, const std::string &to);

class FileSystem 
{
private:
    static std::string (*Builder) (const std::string &path);

public:
    static std::string GetPath(const std::string &path);

private:
    static std::string const &GetRoot();
    static Builder GetPathBuilder();
    static std::string GetPathRelativeRoot(const std::string &path);
    static std::string GetPathRelativeBinary(const std::string &path);
};